use_frameworks!

platform :ios, '8.0'

project 'BaseViewClass.xcworkspace'

target 'BaseViewClass_Example' do
  pod 'BaseViewClass', :path => '../'

  target 'BaseViewClass_Tests' do
    inherit! :search_paths

    
  end
end
